# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: intellectia
      MYSQL_USER: intellectiauser
      MYSQL_PASSWORD: intellectiapassword
      MYSQL_CONNECTION_LIMIT: 100
      MYSQL_WAIT_TIMEOUT: 3600
    ports:
      - "3306:3306"  # Expose MySQL port for external connections
    container_name: mysql-db    
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    container_name: adminer
    networks:
      - mynetwork

  redis-server:
    restart: always
    image: redis
    container_name: redis-server
    ports:
      - "6380:6379"
    volumes:
      - ./redis:/data
    networks:
      - mynetwork

volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local

networks:
  mynetwork:
    driver: bridge
